package Clases;
// Generated 25/11/2016 15:56:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private Inmueble inmueble;
     private Date fecha= new Date();;
     //private Set historiaventas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente, Inmueble inmueble, Date fecha) {
        this.cliente = cliente;
        this.inmueble = inmueble;
        this.fecha = fecha;
    }
    public Factura(Cliente cliente, Inmueble inmueble, Date fecha, Set historiaventas) {
       this.cliente = cliente;
       this.inmueble = inmueble;
       this.fecha = fecha;
       //this.historiaventas = historiaventas;
    }
    public Factura(Inmueble inmuebleVendido, Cliente cliente) {
       this.cliente = cliente;
       this.inmueble = inmuebleVendido;
    }

   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
//    public Set getHistoriaventas() {
//        return this.historiaventas;
//    }
//    
//    public void setHistoriaventas(Set historiaventas) {
//       this.historiaventas = historiaventas;
//    }




}


