package Clases;
// Generated 25/11/2016 16:25:32 by Hibernate Tools 4.3.1



/**
 * Historiaventa generated by hbm2java
 */
public class Historiaventa  implements java.io.Serializable {


     private Integer idhistoriaVenta;
     private Factura factura;
     private Vendedor vendedor;

    public Historiaventa() {
    }

    public Historiaventa(Factura factura, Vendedor vendedor) {
       this.factura = factura;
       this.vendedor = vendedor;
    }
   
    public Integer getIdhistoriaVenta() {
        return this.idhistoriaVenta;
    }
    
    public void setIdhistoriaVenta(Integer idhistoriaVenta) {
        this.idhistoriaVenta = idhistoriaVenta;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }




}


