package Clases;
// Generated 24/11/2016 22:56:09 by Hibernate Tools 4.3.1



/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private Integer idLocalidad;
     private String localidad;

    public Localidad() {
    }

    public Localidad(String localidad) {
       this.localidad = localidad;
    }
   
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


