package Clases;
// Generated 08-nov-2016 20:43:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private Integer idLocalidad;
 //    private Provincia provincia;
     private String localidad;
 //    private Set clientes = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(/*Provincia provincia, */String localidad) {
  //      this.provincia = provincia;
        this.localidad = localidad;
    }
/*    public Localidad(Provincia provincia, String localidad, Set clientes) {
       this.provincia = provincia;
       this.localidad = localidad;
       this.clientes = clientes;
    }
  */ 
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
/*    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
*/    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
/*    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
*/

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        /*if (getClass() != obj.getClass()) {
            return false;
        }*/
        final Localidad other = (Localidad) obj;
        if (!Objects.equals(this.localidad, other.getLocalidad())) {
            return false;
        }
        if (!Objects.equals(this.idLocalidad, other.getIdLocalidad())) {
            return false;
        }
        return true;
    }



}


