package Clases;
// Generated 31-oct-2016 15:38:36 by Hibernate Tools 4.3.1



/**
 * Propietario generated by hbm2java
 */
public class Propietario  implements java.io.Serializable {


     private Integer idPropietario;
     private Localidad localidad;
     private Provincia provincia;
     private String nombre;
     private String apellido;
     private int tipoDoc;
     private int numeroDoc;
     private String domicilio;
     private int alturaDomicilio;
     private int telefono;
     private String correo;

    public Propietario() {
    }

    public Propietario(Localidad localidad, Provincia provincia, String nombre, String apellido, int tipoDoc, int numeroDoc, String domicilio, int alturaDomicilio, int telefono, String correo) {
       this.localidad = localidad;
       this.provincia = provincia;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipoDoc = tipoDoc;
       this.numeroDoc = numeroDoc;
       this.domicilio = domicilio;
       this.alturaDomicilio = alturaDomicilio;
       this.telefono = telefono;
       this.correo = correo;
    }
   
    public Integer getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(Integer idPropietario) {
        this.idPropietario = idPropietario;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(int tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public int getNumeroDoc() {
        return this.numeroDoc;
    }
    
    public void setNumeroDoc(int numeroDoc) {
        this.numeroDoc = numeroDoc;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public int getAlturaDomicilio() {
        return this.alturaDomicilio;
    }
    
    public void setAlturaDomicilio(int alturaDomicilio) {
        this.alturaDomicilio = alturaDomicilio;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


