package Clases;
// Generated 08-nov-2016 20:43:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer idprovincia;
     private String provincia;
//     private Set clientes = new HashSet(0);
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(String provincia) {
        this.provincia = provincia;
    }
    public Provincia(String provincia/*, Set clientes*/, Set localidads) {
       this.provincia = provincia;
//       this.clientes = clientes;
       this.localidads = localidads;
    }
   
    public Integer getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(Integer idprovincia) {
        this.idprovincia = idprovincia;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
 /*   public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
 */   public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


