package Clases;
// Generated 08/11/2016 20:04:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idreserva;
     private Cliente cliente;
     private Inmueble inmueble;
     private Date fechaHasta;
     private double importe;

    public Reserva() {
    }

    public Reserva(Cliente cliente, Inmueble inmueble, Date fechaHasta, double importe) {
       this.cliente = cliente;
       this.inmueble = inmueble;
       this.fechaHasta = fechaHasta;
       this.importe = importe;
    }
    
    public Integer getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(Integer idreserva) {
        this.idreserva = idreserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Reserva other = (Reserva) obj;
        if (Double.doubleToLongBits(this.importe) != Double.doubleToLongBits(other.importe)) {
            return false;
        }
        if (!Objects.equals(this.idreserva, other.idreserva)) {
            return false;
        }
        if (!Objects.equals(this.cliente, other.cliente)) {
            return false;
        }
        if (!Objects.equals(this.inmueble, other.inmueble)) {
            return false;
        }
        if (!Objects.equals(this.fechaHasta, other.fechaHasta)) {
            return false;
        }
        return true;
    }

    
}
