package Clases;
// Generated 08/11/2016 20:04:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idreserva;
     private Cliente cliente;
     private Inmueble inmueble;
     private Date fechaHasta;
     private float importe;

    public Reserva() {
    }

    public Reserva(Cliente cliente, Inmueble inmueble, Date fechaHasta, float importe) {
       this.cliente = cliente;
       this.inmueble = inmueble;
       this.fechaHasta = fechaHasta;
       this.importe = importe;
    }
    
    public Integer getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(Integer idreserva) {
        this.idreserva = idreserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }

}