package Clases;
// Generated 08-nov-2016 20:43:30 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String nombre;
     private String contrasenia;
     private Integer perfil;

    public Usuario() {
    }

	
    public Usuario(String nombre) {
        this.nombre = nombre;
    }
    public Usuario(String nombre, String contrasenia, Integer perfil) {
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.perfil = perfil;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Integer getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Integer perfil) {
        this.perfil = perfil;
    }




}


