package Clases;
// Generated 24/11/2016 22:56:09 by Hibernate Tools 4.3.1

import Clases.Localidad;
import Clases.Provincia;




/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer idVendedor;
     private Localidad localidad;
     private Provincia provincia;
     private Integer tipoDoc;
     private Integer numDoc;
     private String nombre;
     private String apellido;
     private String email;
     private String domicilio;
     private String alturaDomicilio;
     private String telefono;
     private String contrasenia;

    public Vendedor() {
    }

    public Vendedor(Localidad localidad, Provincia provincia, Integer tipoDoc, Integer numDoc, String nombre, String apellido, String email, String domicilio, String alturaDomicilio, String telefono, String contrasenia) {
       this.localidad = localidad;
       this.provincia = provincia;
       this.tipoDoc = tipoDoc;
       this.numDoc = numDoc;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.domicilio = domicilio;
       this.alturaDomicilio = alturaDomicilio;
       this.telefono = telefono;
       this.contrasenia = contrasenia;
    }
   
    public Integer getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public Integer getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(Integer tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public Integer getNumDoc() {
        return this.numDoc;
    }
    
    public void setNumDoc(Integer numDoc) {
        this.numDoc = numDoc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getAlturaDomicilio() {
        return this.alturaDomicilio;
    }
    
    public void setAlturaDomicilio(String alturaDomicilio) {
        this.alturaDomicilio = alturaDomicilio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }




}


